name: Sync to Hugging Face
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install huggingface_hub
          hf auth login --token $HF_TOKEN
          
          rm -rf docs/images/
          
          # यहाँ हमने --exclude कमांड जोड़ दिया है। 
          # अब यह टूल safetensors, json और LFS फाइलों को छोड़कर बाकी सब सिंक कर देगा।
          hf upload Veda-Labs/Vedika-4.1-flash . . --exclude "*.safetensors" --exclude "*.json" --exclude ".gitattributes" --exclude ".git/*"
